### ISSUE TITLE
Investigate Validation Errors from production logs

### ISSUE THREAD

**Issue by rtyler** [jenkins-infra/uplink#21]
```
error: BadRequest: Validation error
    at new BadRequest (/srv/uplink/node_modules/@feathersjs/errors/lib/index.js:86:17)
    at errorHandler (/srv/uplink/node_modules/feathers-sequelize/lib/utils.js:13:25)
    at tryCatcher (/srv/uplink/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/srv/uplink/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/srv/uplink/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/srv/uplink/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/srv/uplink/node_modules/bluebird/js/release/promise.js:690:18)
    at _drainQueueStep (/srv/uplink/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/srv/uplink/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/srv/uplink/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/srv/uplink/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:763:18)
    at tryOnImmediate (timers.js:734:5)
    at processImmediate (timers.js:716:5)
    at process.topLevelDomainCallback (domain.js:102:23)
```

Looks like some data is not coming through cleanly, but this message is really not being helpful.

**Comment by rtyler** [comment]
I _believe_ that this is the types denormalization at work, but need to validate that by squelching that error message.
